### ISSUE TITLE
One error occurs when running the notebook

### ISSUE THREAD

**Issue by louisliuwei** [strath-sdr/rfsoc_qpsk#10]
![error](https://user-images.githubusercontent.com/29596792/54348064-3bd53780-4683-11e9-8cec-62a83250fad0.PNG)

**Comment by louisliuwei** [comment]
and there is no any output after exacting the following code.
![image](https://user-images.githubusercontent.com/29596792/54348541-362c2180-4684-11e9-9087-9e602d9db4eb.png)
I do not know if it result from the following error when installing jupyter labextension
![image](https://user-images.githubusercontent.com/29596792/54348381-e2213d00-4683-11e9-9de0-300f233716ad.png)

**Comment by jogomojo** [comment]
Can you check you are using **Jupyter Lab** by explicitly connecting to `192.168.2.99:9000/lab`. The extensions will not work in a regular Notebook.

**Comment by reykowski** [comment]
Hi Josh,
I got the notebook running, but I do not see any plots.
I do however see the two sliders at the end of the notebook and have confirmed that they are working.
Here some things that I noticed:
The Jupyter extensions seem to be already integrated in the Xilinx Pynq distribution image for the ZCU111.
When I connect, I cannot use the port 9000 that you suggested. It only works with 9090.
Instead of a plot, I see a text description:

FigureWidget({
    'data': [{'name': ' I',
              'type': 'scatter',
              'uid': 'f294c193-ede…

So it seems it is trying, but the widget is not working.

Thanks in advance,
Arne

**Comment by reykowski** [comment]
One more thing:
It looks like plotly requires registration and credentials:
https://plot.ly/python/getting-started/
Could that be an issue?
Arne

**Comment by jogomojo** [comment]
Hi Arne, 

Please check you are running Jupyter Lab. If your port is 9090 then try `192.168.2.99:9090/lab` instead. Lab is noticeably different from Notebook but may not default to it on boot. The output you gave is exactly what you'd expect if Notebook was opened instead of Lab or, if the extensions were not installed at all.

We are using the offline version of Plotly that does not require credentials, so that shouldn't be an issue. 

The quick start setup was tested with a fresh image before making the repo public, but I will try again if you are still having issues.

**Comment by reykowski** [comment]
Josh,
Thanks.
I followed the instructions to the teeth and now it seems to be working.
Arne

**Comment by jogomojo** [comment]
> and there is no any output after exacting the following code.
> ![image](https://user-images.githubusercontent.com/29596792/54348541-362c2180-4684-11e9-9087-9e602d9db4eb.png)
> I do not know if it result from the following error when installing jupyter labextension
> ![image](https://user-images.githubusercontent.com/29596792/54348381-e2213d00-4683-11e9-9de0-300f233716ad.png)

**Comment by jogomojo** [comment]
> and there is no any output after exacting the following code.
> ![image](https://user-images.githubusercontent.com/29596792/54348541-362c2180-4684-11e9-9087-9e602d9db4eb.png)
> I do not know if it result from the following error when installing jupyter labextension
> ![image](https://user-images.githubusercontent.com/29596792/54348381-e2213d00-4683-11e9-9de0-300f233716ad.png)

Has this issue been resolved @louisliuwei ?

**Comment by louisliuwei** [comment]
Hi jogomojo, It works now by using Jupyter Lab by explicitly connecting to 192.168.2.99:9000/lab.

**Comment by louisliuwei** [comment]
> > and there is no any output after exacting the following code.
> > ![image](https://user-images.githubusercontent.com/29596792/54348541-362c2180-4684-11e9-9087-9e602d9db4eb.png)
> > I do not know if it result from the following error when installing jupyter labextension
> > ![image](https://user-images.githubusercontent.com/29596792/54348381-e2213d00-4683-11e9-9de0-300f233716ad.png)
> 
> Has this issue been resolved @louisliuwei ?

The issue is resolved. The reason is I ran the notebook directly on Chrome, not using Jupyter Lab by explicitly connecting to 192.168.2.99:9000/lab.
