### ISSUE TITLE
How to change QPSK data rate to 10kbps?

### ISSUE THREAD

**Issue by yoshimifujii** [strath-sdr/rfsoc_qpsk#25]
Hi,
I'm trying to change the QPSK symbol rate to 10kbps. 
I just change Rb = 10000(from 1000) and R_CIC = 320(from 3200). 
After that, I build the Tx/Rx IPs and the bitstream file. 
But, observing the RF output of qpsk_tx, the signal BW still seems about 1kHz. 
Could you tell me what other configurations to be changed?

**Comment by jogomojo** [comment]
Hi JG,

There's a coupe of things to check here first:

- Check the sample time of the inputs and outputs of each IP to make sure they make sense in relation to the decimation/interpolation stages.
- Make sure you have changed the value of `Rb` and `R_CIC` in **both** the *AXI_QPSK_Tx.slx* **and** the *axi_qpsk_rx_dec.slx* files.

Try those out and, if they don't work, I'll have another look.

Josh

**Comment by kurtulmehtap** [comment]
Hi,
I would like to change the bitrate to 10 Mbps, If I change the Rb = 10000000(from 1000) what should I use for the R_CIC value?
Is there a formula for different bit rates?

**Comment by chackn** [comment]
We are on the way toward over 10Msps=20Mbps and now, we are struggling with 3.2Mbps. 
qpsk_tx seems to have no problem. 
How to determine K factors for loop filters in qpsk_rx_tsync block?
I modified the block, changed the fixed values to variables and pulled them out so that I can change their values from Python.
